// ignore_for_file: unused_import, non_constant_identifier_names

import 'package:flutter/material.dart';

class CarModel {
  final int id;
  final String modelo;
  final String location;
  final double price;
  final int Kilometros;
  final int fecha;
  final String Puerta;
  final String Descripcion;
  final String imageAsset;
   int quantity; 

  CarModel({
    required this.id,
    required this.modelo,
    required this.location,
    required this.price,
    required this.imageAsset,
    required this.Kilometros,
    required this.fecha,
    required this.Puerta,
    required this.Descripcion,
    required this.quantity
  });

  get totalPrice {
    return quantity * price;
  }
  
   Map<String, dynamic> toMap() {
    return {
      'id': id,
      'modelo': modelo,
      'location': location,
      'price': price,
      'imageAsset': imageAsset,
      'Kilometros': Kilometros,
      'fecha': fecha,
      'Puerta': Puerta,
      'Descripcion': Descripcion,
    };
  }
}

List<CarModel> carModels = [
  CarModel(
    id: 1,
    modelo: 'Chevrolet Onix',
    location: 'Peru - Lima - Los Olivos',
    price: 11500,
    imageAsset: 'assets/images/ChevroletOnix.png', 
    Kilometros: 10000,
    fecha: 2019,
    Puerta: '4',
    Descripcion: 'El Chevrolet Onix es un automóvil de turismo del segmento B producido por el fabricante estadounidense Chevrolet para América del Sur. Es un cinco plazas con carrocerías hatchback de cinco puertas y sedán de cuatro puertas, y motor delantero transversal y tracción delantera. Reemplazó al Chevrolet Celta y al Chevrolet Prisma. Se presentó en el Salón del Automóvil de San Pablo de 2012 y se comenzó a vender en Brasil en noviembre de 2012. En 2013 se lanzó en Argentina, y en 2014 en Colombia, Ecuador, Paraguay, Perú, Uruguay y Venezuela. En 2015 se lanzó en México, y en 2017 en Bolivia. En 2019 se lanzó en Chile. En 2020 se lanzó en Costa Rica, Panamá y República Dominicana. En 2021 se lanzó en Guatemala, Honduras, Nicaragua y El Salvador.',
    quantity: 0,
  ),
  CarModel(
    id: 2,
    modelo: 'Kia Rio',
    location: 'Peru - Lima - San Miguel',
    price: 12500,
    imageAsset: 'assets/images/KiaRio.png', 
    Kilometros: 20000,
    fecha: 2018,
    Puerta: '4',
    Descripcion: 'El Kia Rio es un automóvil de turismo del segmento B producido por el fabricante surcoreano Kia Motors desde agosto de 2000 hasta la actualidad. Es un cinco plazas con carrocerías hatchback de cinco puertas y sedán de cuatro puertas, y motor delantero transversal y tracción delantera. Reemplazó al Kia Pride y al Kia Avella. Se presentó en el Salón del Automóvil de Ginebra de 2000 y se comenzó a vender en Corea del Sur en agosto de 2000. En 2001 se lanzó en Europa, y en 2002 en América. En 2005 se lanzó la segunda generación, en 2011 la tercera y en 2017 la cuarta. En 2018 se lanzó la cuarta generación en América. En 2020 se lanzó la cuarta generación en Europa. En 2021 se lanzó la cuarta generación en Corea del Sur.',
    quantity: 0
  ),
   CarModel(
    id: 3,
    modelo: 'Nissan Sentra',
    location: 'Peru - Lima - Surco',
    price: 14000,
     imageAsset: 'assets/images/NissanSentra.png', 
      Kilometros: 30000,
    fecha: 2017,
    Puerta: '4',
    Descripcion: 'El Nissan Sentra es un automóvil de turismo del segmento C producido por el fabricante japonés Nissan desde 1982. Es un cinco plazas con carrocerías sedán de cuatro puertas y hatchback de cinco puertas, y motor delantero transversal y tracción delantera. Reemplazó al Nissan Sunny y al Nissan Pulsar. Se presentó en el Salón del Automóvil de Tokio de 1981 y se comenzó a vender en Japón en mayo de 1982. En 1983 se lanzó en Estados Unidos, y en 1984 en Europa. En 1986 se lanzó la segunda generación, en 1990 la tercera, en 1995 la cuarta, en 2000 la quinta, en 2006 la sexta, en 2012 la séptima y en 2019 la octava. En 2020 se lanzó la octava generación en América. En 2021 se lanzó la octava generación en Europa.',
    quantity: 0
  ),
   CarModel(
    id: 4,
    modelo: 'Toyota Corolla',
    location: 'Peru - Lima - Lince',
    price: 16000,
    imageAsset: 'assets/images/ToyotaCorolla.png', 
    Kilometros: 40000,
    fecha: 2016,
    Puerta: '4',
    Descripcion: 'El Toyota Corolla es un automóvil de turismo del segmento C producido por el fabricante japonés Toyota desde 1966. Es el automóvil más vendido de la historia, con más de 40 millones de unidades vendidas. El nombre Corolla proviene de la corona de flores del latín que significa pequeña corona. Es un cinco plazas con carrocerías sedán de cuatro puertas, hatchback de cinco puertas y familiar de cinco puertas, y motor delantero transversal y tracción delantera. Reemplazó al Toyota Publica y al Toyota 1000. Se presentó en octubre de 1966 y se comenzó a vender en Japón en noviembre de 1966. En 1967 se lanzó en Europa, y en 1968 en América. En 1970 se lanzó la segunda generación, en 1974 la tercera, en 1979 la cuarta, en 1983 la quinta, en 1987 la sexta, en 1991 la séptima, en 1995 la octava, en 2000 la novena, en 2006 la décima, en 2012 la undécima y en 2018 la duodécima. En 2019 se lanzó la duodécima generación en América. En 2020 se lanzó la duodécima generación en Europa.',
    quantity: 0
  ),
   CarModel(
    id: 5,
    modelo: 'Hyundai Elantra',
    location: 'Peru - Lima - El Agustino',
    price: 17000,
    imageAsset: 'assets/images/HyundaiElantra.png',
    Kilometros: 50000,
    fecha: 2015,
    Puerta: '4',
    Descripcion: 'El Hyundai Elantra es un automóvil de turismo del segmento C producido por el fabricante surcoreano Hyundai Motor Company desde 1990. Es un cinco plazas con carrocerías sedán de cuatro puertas y hatchback de cinco puertas, y motor delantero transversal y tracción delantera. Reemplazó al Hyundai Stellar y al Hyundai Pony. Se presentó en el Salón del Automóvil de Seúl de 1990 y se comenzó a vender en Corea del Sur en octubre de 1990. En 1991 se lanzó en Europa, y en 1992 en América. En 1995 se lanzó la segunda generación, en 2000 la tercera, en 2006 la cuarta, en 2010 la quinta, en 2015 la sexta y en 2020 la séptima. En 2021 se lanzó la séptima generación en América. En 2022 se lanzará la séptima generación en Europa.',
    quantity: 0
  ),
   CarModel(
    id: 5,
    modelo: 'Nissan X-Trail',
    location: 'Peru - Lima - San Isidro',
    price: 22000,
     imageAsset: 'assets/images/NissanXTrail.png',
    Kilometros: 60000,
    fecha: 2014,
    Puerta: '4',
    Descripcion: 'El Nissan X-Trail es un automóvil todoterreno del segmento C producido por el fabricante japonés Nissan desde 2001. Es un cinco plazas con carrocerías todoterreno de cinco puertas y familiar de cinco puertas, y motor delantero transversal y tracción delantera o a las cuatro ruedas. Reemplazó al Nissan Rasheen y al Nissan Terrano II. Se presentó en el Salón del Automóvil de Tokio de 2000 y se comenzó a vender en Japón en noviembre de 2000. En 2001 se lanzó en Europa, y en 2002 en América. En 2007 se lanzó la segunda generación, en 2013 la tercera y en 2021 la cuarta. En 2021 se lanzó la cuarta generación en América. En 2022 se lanzará la cuarta generación en Europa.',
    quantity: 0
  ),
  CarModel(
  id: 6,
  modelo: 'Ferrari 488 GTB',
  location: 'Italy - Maranello',
  price: 350000,  
  imageAsset: 'assets/images/Ferrari_488_GTB.png', 
  Kilometros: 5000,  
  fecha: 2022, 
  Puerta: '2',  
  Descripcion: 'El Ferrari 488 GTB es un automóvil deportivo de altas prestaciones producido por el fabricante italiano Ferrari. Fue presentado en el Salón del Automóvil de Ginebra de 2015 y es el sucesor del Ferrari 458 Italia. Incorpora un motor V8 turboalimentado de 3.9 litros capaz de generar una potencia máxima de aproximadamente 670 CV. Es reconocido por su elevado rendimiento y diseño aerodinámico avanzado.',
  quantity: 0,
),

CarModel(
  id: 7,
  modelo: 'Mercedes-AMG Petronas Formula 1 W12',
  location: 'Germany - Brackley',
  price: 20000000, 
  imageAsset: 'assets/images/MercedesAMGPetronasFormula1W12.png', 
  Kilometros: 0,  
  fecha: 2023,  
  Puerta: '0', 
  Descripcion: 'El Mercedes-AMG Petronas Formula 1 W12 es un monoplaza de Fórmula 1 desarrollado por el equipo Mercedes-AMG Petronas Formula One Team para la temporada de Fórmula 1 de 2023. Es un monoplaza de altas prestaciones diseñado para competir en el campeonato de Fórmula 1, caracterizado por su tecnología avanzada y altas velocidades.',
  quantity: 0,
),
CarModel(
  id: 8,
  modelo: 'Porsche 911 Carrera',
  location: 'Germany - Stuttgart',
  price: 150000,  
  imageAsset: 'assets/images/Porsche911Carrera.png', 
  Kilometros: 10000,  
  fecha: 2022,  
  Puerta: '2',  
  Descripcion: 'El Porsche 911 Carrera es un icónico automóvil deportivo producido por el fabricante alemán Porsche. Es conocido por su diseño distintivo y altas prestaciones, equipado con motores potentes y avanzada tecnología.',
  quantity: 0,
),
CarModel(
  id: 9,
  modelo: 'Audi R8 V10',
  location: 'Germany - Ingolstadt',
  price: 180000,  
  imageAsset: 'assets/images/AudiR8V10.png', 
  Kilometros: 8000,  
  fecha: 2023,  
  Puerta: '2',  
  Descripcion: 'El Audi R8 V10 es un impresionante superdeportivo fabricado por la marca alemana Audi. Equipado con un potente motor V10, proporciona un rendimiento excepcional y un diseño aerodinámico.',
  quantity: 0,
),
CarModel(
  id: 10,
  modelo: 'Ford Mustang Shelby GT500',
  location: 'USA - Dearborn',
  price: 160000,  
  imageAsset: 'assets/images/FordMustangShelbyGT500.png', 
  Kilometros: 6000,  
  fecha: 2022,  
  Puerta: '2',  
  Descripcion: 'El Ford Mustang Shelby GT500 es un poderoso muscle car de altas prestaciones desarrollado por Ford. Es conocido por su potencia, velocidad y un diseño icónico que lo distingue en la carretera.',
  quantity: 0,
),
CarModel(
  id: 11,
  modelo: 'Batmobile',
  location: 'Gotham City',
  price: 1000000,  
  imageAsset: 'assets/images/Batmobile.png', 
  Kilometros: 0,  
  fecha: 2023,  
  Puerta: '2',  
  Descripcion: 'El Batmobile es un vehículo ficticio inspirado en el cómic de Batman. Es el vehículo de transporte personal de Batman, diseñado para ayudarlo en su lucha contra el crimen en Gotham City. Con su diseño distintivo y tecnología avanzada, el Batmobile es un ícono de la saga de Batman.',
  quantity: 0,
),
CarModel(
  id: 12,
  modelo: 'Knight Industries Two Thousand (KITT)',
  location: 'USA',
  price: 500000, 
  imageAsset: 'assets/images/KIIT.png', 
  Kilometros: 0,  
  fecha: 1982, 
  Puerta: '2', 
  Descripcion: 'Knight Industries Two Thousand (KITT) es un vehículo ficticio de la serie de televisión "Auto Fantástico" (Knight Rider). KITT es un automóvil avanzado con inteligencia artificial que asiste a su conductor Michael Knight en sus misiones contra el crimen. Destacado por su habilidad para hablar, pensar y conducirse de manera autónoma, el KITT se ha convertido en un ícono de la cultura pop.',
  quantity: 0,
),
CarModel(
  id: 13,
  modelo: 'DeLorean DMC-12 (Volver al Futuro)',
  location: 'Hill Valley, California',
  price: 80000,  
  imageAsset: 'assets/images/DeLorean.png', 
  Kilometros: 0, 
  fecha: 1981,  
  Puerta: '2',  
  Descripcion: 'El DeLorean DMC-12 es un automóvil deportivo de acero inoxidable fabricado por la empresa estadounidense DeLorean Motor Company. Es conocido por su aparición en la saga cinematográfica "Volver al Futuro", donde se convierte en una máquina del tiempo. El DeLorean de "Volver al Futuro" es icónico por sus puertas de ala de gaviota y su capacidad para viajar en el tiempo.',
  quantity: 0,
),
CarModel(
  id: 15,
  modelo: 'Ecto-1 (Los Cazafantasmas)',
  location: 'New York City',
  price: 120000,  
  imageAsset: 'assets/images/Ecto1.png', 
  Kilometros: 0,  
  fecha: 1959,  
  Puerta: '4',  
  Descripcion: 'El Ecto-1 es un vehículo utilizado por los Cazafantasmas en la franquicia cinematográfica "Ghostbusters" (Los Cazafantasmas). Es un automóvil de 1959 Cadillac Miller-Meteor modificado para contener equipo de detección paranormal y captura de fantasmas. El Ecto-1 es un ícono de la cultura pop y es conocido por su sirena y luces distintivas.',
  quantity: 0,
),
CarModel(
  id: 16,
  modelo: 'General Lee (Los Dukes de Hazzard)',
  location: 'Hazzard County',
  price: 80000,  
  imageAsset: 'assets/images/GeneralLee.png', 
  Kilometros: 0, 
  fecha: 1969,  
  Puerta: '2',  
  Descripcion: 'El General Lee es un Dodge Charger de 1969 utilizado en la serie de televisión "The Dukes of Hazzard" (Los Dukes de Hazzard). Es reconocido por su color naranja brillante, el número 01 en los laterales y su distintivo techo pintado. El General Lee es conocido por sus acrobacias y saltos en la serie.',
  quantity: 0,
),
CarModel(
  id: 17,
  modelo: 'Rayo McQueen (Cars)',
  location: 'Radiador Springs',
  price: 60000,  
  imageAsset: 'assets/images/RayoMcQueen.png', 
  Kilometros: 0, 
  fecha: 2006,  
  Puerta: '2',  
  Descripcion: 'Rayo McQueen es el protagonista de la película animada "Cars" de Disney-Pixar. Es un auto de carreras que termina en el pequeño pueblo de Radiador Springs, donde aprende lecciones valiosas sobre la vida y la amistad. Conocido por su número de carrera "95", Rayo McQueen se ha convertido en un personaje querido en la cultura popular.',
  quantity: 0,
),
CarModel(
  id: 18,
  modelo: 'Tron Light Cycle',
  location: 'Grid',
  price: 75000,  
  imageAsset: 'assets/images/TronLightCycle.png', 
  Kilometros: 0, 
  fecha: 2010,  
  Puerta: '0',  
  Descripcion: "Tron Lightcycle/Run dispone de una cubierta de 15.240 metros cuadrados que la protege de las inclemencias del tiempo de Florida, cuenta con 32 metros de altura y más de 1.200 luces, que componen por sí solas un espectáculo nocturno.",
  quantity: 0,
),
CarModel(
  id: 18,
  modelo: 'Mystery Machine (Scooby-Doo)',
  location: 'Coolsville',
  price: 30000,  
  imageAsset: 'assets/images/MysteryMachine.png', 
  Kilometros: 0, 
  fecha: 1969,  
  Puerta: '4',  
  Descripcion: 'El Mystery Machine es la icónica furgoneta utilizada por Scooby-Doo y su pandilla en la serie de televisión "Scooby-Doo". Es reconocida por su diseño psicodélico y colores brillantes. El Mystery Machine es símbolo de aventuras y misterios sin resolver que la pandilla aborda y resuelve en cada episodio.',
  quantity: 0,
),
CarModel(
  id: 19,
  modelo: 'Ford Gran Torino (Starsky & Hutch)',
  location: 'Bay City, California',
  price: 60000,  
  imageAsset: 'assets/images/FordGranTorino.png', 
  Kilometros: 0, 
  fecha: 1974,  
  Puerta: '2',  
  Descripcion: 'El Ford Gran Torino es un vehículo que se hizo famoso en la serie de televisión "Starsky & Hutch". Es reconocido por su diseño distintivo, su color rojo brillante y su participación en persecuciones de alta velocidad en la serie. El Ford Gran Torino es un ícono de la cultura pop de los años 70.',
  quantity: 0,
),
CarModel(
  id: 20,
  modelo: 'Quinjet (Los Vengadores)',
  location: 'New York City',
  price: 10000000,  
  imageAsset: 'assets/images/Quinjet.png', 
  Kilometros: 0,  
  fecha: 2012,  
  Puerta: '4',  
  Descripcion: 'El Quinjet es un vehículo aéreo utilizado por los Vengadores en el Universo Cinematográfico de Marvel (MCU). Es un avanzado transporte equipado con tecnología de punta y capacidades de combate. El Quinjet es fundamental para las misiones de los Vengadores y ha aparecido en varias películas de Marvel.',
  quantity: 0,
),
CarModel(
  id: 21,
  modelo: 'Helitransporte (S.H.I.E.L.D.)',
  location: 'Unknown',
  price: 500000000, 
  imageAsset: 'assets/images/Helicarrier.png', 
  Kilometros: 0,  
  fecha: 2012,  
  Puerta: '0', 
  Descripcion: 'El Helitransporte, también conocido como "Helicarrier", es un vehículo volador utilizado por S.H.I.E.L.D. en el Universo Cinematográfico de Marvel (MCU). Es una plataforma aérea de alta tecnología que sirve como centro de comando móvil y base de operaciones para los Vengadores y otros agentes de S.H.I.E.L.D.',
  quantity: 0,
),
CarModel(
  id: 22,
  modelo: 'McLaren F1 Google Edition',
  location: 'United Kingdom',
  price: 250000,
  imageAsset: 'assets/images/McLaren.png',
  Kilometros: 5000,
  fecha: 2022,
  Puerta: '2',
  Descripcion: 'El McLaren es un automóvil deportivo de alta gama producido por el fabricante británico McLaren Automotive. Es reconocido por su rendimiento excepcional y diseño aerodinámico. Este modelo en particular tiene el logo de Google en los tapacubos, destacando su asociación con la tecnología y la innovación.',
  quantity: 3,
)
];
